# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 05:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0004_user1_picture_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user1',
            name='picture_url',
            field=models.CharField(default=b'https://jtkwriting.files.wordpress.com/2015/01/7rf-d-60.jpg', max_length=1000),
        ),
    ]
