# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 13:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0008_auto_20171204_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='user_tag',
            field=models.CharField(max_length=50),
        ),
    ]
