# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 14:42
from __future__ import unicode_literals

from django.db import migrations
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0013_auto_20171204_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientinfo',
            name='client_meta',
            field=picklefield.fields.PickledObjectField(default={}, editable=False),
        ),
    ]
