# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 14:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0015_auto_20171204_2015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientinfo',
            name='client_meta',
        ),
    ]
