# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-11 04:21
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0017_auto_20171211_0000'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientinfo',
            name='client_meta',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
    ]
