# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-11 16:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0018_clientinfo_client_meta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientinfo',
            name='seen',
        ),
        migrations.AddField(
            model_name='clientinfo',
            name='times_seen',
            field=models.IntegerField(default=0),
        ),
    ]
